spring.application.name=main-service
server.port=8083

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:internship-project-db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:satorugod1}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true

spring.jpa.show-sql=true

logging.level.root = INFO
logging.level.com.kz.internship_project=DEBUG

logging.level.org.hibernate.sql=DEBUG
logging.file.name=logs/app.log


logging.level.liquibase=DEBUG
logging.level.org.liquibase=DEBUG

