name: Integration Tests

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Скачать код из репозитория
        uses: actions/checkout@v4

      - name: Установить Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Дать права на исполнение gradlew
        run: chmod +x gradlew

      # Добавляем шаг предварительного pull образ(ов)
      - name: Предварительно скачать Docker образ
        run: |
          docker pull postgres:16-alpine
          docker pull quay.io/minio/minio

      - name: Запустить интеграционные тесты
        run: ./gradlew test